name: Build
on:
  push:
    branches:
    - main 
    paths:
    - src/**
    - Cargo.toml
    - '.github/workflows/build.yml'
env:
  PROJECT_NAME: 'chmmod-create'
jobs:
  build:
    if: 'contains(github.event.head_commit.message, ''[build]'')'
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
        - name: linux-amd64
          runner: ubuntu-latest
          target: x86_64-unknown-linux-gnu
          lib-suffix: '.so'
        - name: win-amd64
          runner: windows-latest
          target: x86_64-pc-windows-msvc
          lib-suffix: '.dll'
        - name: macos-amd64
          runner: macos-latest
          target: x86_64-apple-darwin
          lib-suffix: '.dylib'
        - name: macos-arm64
          runner: macos-latest
          target: aarch64-apple-darwin
          lib-suffix: '.dylib'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    - name: Setup Cache
      uses: Swatinem/rust-cache@v2
    - name: Create Dist Directory
      run: mkdir -p dist
    - name: Build Library
      run: cargo build --verbose --locked --release --target ${{ matrix.target }}
    - name: Prepare Release Binary
      run: |
        BIN_SUFFIX=""
        if [[ "${{ matrix.runner }}" == "windows-latest" ]]; then
          BIN_SUFFIX=".exe"
        fi
        for BINARY in $(ls target/${{ matrix.target }}/release/); do
          FILE_PATH="target/${{ matrix.target }}/release/$BINARY"
          if [[ "${{ matrix.runner }}" == "windows-latest" ]]; then
            if [[ "$BINARY" == *"$BIN_SUFFIX" ]]; then
              RELEASE_BINARY="${BINARY%.exe}-${{ matrix.name }}$BIN_SUFFIX"
              mv "$FILE_PATH" "./dist/$RELEASE_BINARY"
            fi
          else
            if [[ -f "$FILE_PATH" && -x "$FILE_PATH" ]]; then
              RELEASE_BINARY="${BINARY}-${{ matrix.name }}"
              mv "$FILE_PATH" "./dist/$RELEASE_BINARY"
            fi
          fi
        done
      shell: bash
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "chmmod_create-${{ matrix.name }}"
        retention-days: 30
        path: dist/
